### ISSUE TITLE
libvtk -> meshio

### ISSUE THREAD

**Issue by nschloe** [pnavaro/plot_vtk_with_matplotlib#1]
Instead of the huge vtk dependency, you could try [meshio](https://github.com/nschloe/meshio) (a project of mine). Should simplify your code, too.

**Comment by pnavaro** [comment]
It works like a charm. Thank you very much for the tip. I added a [notebook using meshio](https://nbviewer.jupyter.org/github/pnavaro/plot_vtk_with_matplotlib/blob/master/meshio-example.ipynb). Nice work and thanks for sharing.
